<?php require 'Routing.php';
    session_start();
    $path = trim($_SERVER['REQUEST_URI'],'/');
    $path = parse_url($path, PHP_URL_PATH);
    Routing::post('login','SecurityController');
    Routing::post('registerUser','SecurityController');
    Routing::post('changeAcc','SecurityController');
    Routing::get('competitionImages','CompetitionController');
    Routing::get('register','DefaultController');
    Routing::get('admin','SecurityController');
    Routing::get('removeUser','SecurityController');
    Routing::get('','DefaultController');
    Routing::get('evaluate','DefaultController');
    Routing::get('acc','DefaultController');
    Routing::get('leaderboard','DefaultController');
    Routing::get('topic','DefaultController');
    Routing::post('addCP','CompetitionController');
    Routing::post('logout','SecurityController');
    Routing::post('evaluateCI','CompetitionController');
    Routing::post('search','CompetitionController');
    Routing::run($path);
?>